@startuml
actor Читатель
actor Библиотекарь
actor "Система уведомлений"

usecase "Поиск книг" as UC1
usecase "Запись на книги" as UC2
usecase "Возврат книг" as UC3
usecase "Продление срока аренды" as UC4
usecase "Управление запасами книг" as UC5
usecase "Добавление новых книг" as UC6
usecase "Уведомление о возврате" as UC7

Читатель --> UC1
Читатель --> UC2
Читатель --> UC3
Читатель --> UC4

Библиотекарь --> UC5
Библиотекарь --> UC6

"Система уведомлений" --> UC7
UC7 <-- Читатель : Получает уведомление
@enduml
